### ISSUE TITLE
Invalid regular expressions in grammar

### ISSUE THREAD

**Issue by lildude** [hustcer/nu-grammar#1]
👋 from github-linguist/linguist.

I'm in the process of creating the next release and I've seen our grammar compiler has detected the grammar has two invalid regular expressions which may impact the highlighting of some Nushell files:

- repository `vendor/grammars/nu-grammar` (from https://github.com/hustcer/nu-grammar.git) (2 errors)
  - Invalid regex in grammar: `source.nushell` (in `grammars/tmLanguage.json`) contains a malformed regex (regex "`(?<!\w)(?:(\^)|(?![0-9]|(?<=\)|\`...": lookbehind assertion is not fixed length (at offset 42))
  - Invalid regex in grammar: `source.nushell` (in `grammars/tmLanguage.json`) contains a malformed regex (regex "`(?<=\)|\}|\]|\$\w+)(?:\.(?:[\w-]`...": lookbehind assertion is not fixed length (at offset 18))

I suspect these were reported in the output when you added the grammar to Linguistin your original PR but likely missed it.

I won't hold back the release for this to be fixed, but I will be adding this to the list of known grammar issues: https://github.com/github-linguist/linguist/issues/3924. Any fixes you make to this grammar will be pulled in when the next release is made.

**Comment by hustcer** [comment]
OK，thanks, but how to detect invalid regular expressions for `nu-grammar`? So I can make sure that it's fixed

**Comment by lildude** [comment]
We use the compiler [here](https://github.com/github-linguist/linguist/tree/master/tools/grammars) which uses a PCRE library to validate all the regular expressions.

You can do something similar on from the CLI using [`pcretest`](https://www.man7.org/linux/man-pages/man1/pcretest.1.html) or online using something like https://regex101.com/

**Comment by glcraft** [comment]
The regex works in ECMAScript (Javascript) but doesn't work for PCRE and others. That's why it works in vscode but can't work somewhere else.
I'll try to work around this issue to make something which morks for PCRE.

**Comment by hustcer** [comment]
@glcraft Thanks, the grammar file for linguist has been updated just now

**Comment by hustcer** [comment]
Should be closed by https://github.com/nushell/vscode-nushell-lang/pull/137
